services:

  autonomy-evaluation:
    image: ghcr.io/thinking-cars/autonomy_evaluation:v2.0.0
    environment:
      # --- name ------
      NAMESPACE: /
      NAME: autonomy_evaluation
      # --- other -----
      REQUEST_SAMPLES: ~/request_samples
      LOG_LEVEL: ${LOG_LEVEL:-info}
      USE_SIM_TIME: ${USE_SIM_TIME:-true}
      EVALUATION: object_detection_3d
      VISUALIZE: false
      SAMPLE_SOURCE: dataset
      SYNC_TOLERANCE: 0.0
      SAMPLES_PER_REQUEST: 1
      SAMPLE_IDS: ""
      EVALUATION_TIMEOUT: 60.0
      RESULTS_PATH: ""
    command:
      - /bin/bash
      - -ic
      - |
        ros2 launch autonomy_evaluation autonomy_evaluation.launch.py \
          namespace:=$${NAMESPACE} \
          name:=$${NAME} \
          log_level:=$${LOG_LEVEL} \
          use_sim_time:=$${USE_SIM_TIME} \
          evaluation:=$${EVALUATION} \
          visualize:=$${VISUALIZE} \
          sample_source:=$${SAMPLE_SOURCE} \
          sync_tolerance:=$${SYNC_TOLERANCE} \
          samples_per_request:=$${SAMPLES_PER_REQUEST} \
          $${SAMPLE_IDS:+sample_ids:=$${SAMPLE_IDS}} \
          evaluation_timeout:=$${EVALUATION_TIMEOUT} \
          $${RESULTS_PATH:+results_path:=$${RESULTS_PATH}} \
          request_samples:=$${REQUEST_SAMPLES}
