name: ${USER}-autonomy-evaluation

services:

  ## EVALUATION ##

  autonomy_evaluation:
    image: ghcr.io/thinking-cars/autonomy_evaluation:latest
    command:
      - /bin/bash
      - -ic
      - |
        ros2 launch autonomy_evaluation autonomy_evaluation.launch.py \
          evaluation:=object_detection_3d \
          prediction:=/object_list/prediction \
          label:=/object_list/lidar_01 \
          request_samples:=/datasets/request_samples \
          visualize:=true \
          results_path:=results.json
    environment:
      - RMW_IMPLEMENTATION=rmw_fastrtps_cpp
      - DISPLAY=${DISPLAY:-""}
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=all
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
    deploy:
      resources:
          reservations:
            devices:
              - driver: nvidia
                count: all
                capabilities: [gpu]

  ## DATASET ##

  autonomy_datasets:
    image: ghcr.io/thinking-cars/autonomy_datasets:v1.7.0
    command:
      - /bin/bash
      - -ic
      - |
        ros2 launch autonomy_datasets autonomy_datasets.launch.py \
          dataset:=$${DATASET} \
          config:=/params_$${DATASET}.yml \
          wait_for_ack:=false \
          start_paused:=true \
          target_frame_rate:=0.0 \
          rviz:=no
    environment:
      RMW_IMPLEMENTATION: rmw_fastrtps_cpp
      DATASET: ${DATASET}
      HF_TOKEN: ${HF_TOKEN}
    volumes:
      - ./config/params_${DATASET}.yml:/params_${DATASET}.yml
      - $DATASET_DIR:/datasets

  ## SYSTEM UNDER TEST ##

  autoware_lidar_centerpoint:
    profiles:
      - centerpoint
    image: ghcr.io/thinking-cars/autoware_lidar_centerpoint:latest
    environment:
      RMW_IMPLEMENTATION: rmw_fastrtps_cpp
    command:
      - /bin/bash
      - -ic
      - |
        ros2 launch autoware_lidar_centerpoint lidar_centerpoint.launch.xml \
          model_name:=centerpoint_tiny \
          input/pointcloud:=/lidar_01/point_cloud \
          output/objects:=/object_list/prediction \
          use_sim_time:=true
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]

  focalformer3d-detector:
    profiles:
      - focalformer3d
    depends_on:
      - autonomy_datasets
    image: ghcr.io/thinking-cars/focalformer3d_detector:latest
    environment:
      RMW_IMPLEMENTATION: rmw_fastrtps_cpp
    command:
      - /bin/bash
      - -ic
      - |
        ros2 launch focalformer3d_detector focalformer3d_detector_launch.py \
          use_sim_time:=true \
          input_topic:=/lidar_01/point_cloud \
          output_topic:=/object_list/prediction
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
