name: ${USER}-autonomy-evaluation

services:

  ## EVALUATION ##

  autonomy_evaluation:
    extends:
      file: docker-compose.yml
      service: autonomy_evaluation
    image: ghcr.io/thinking-cars/autonomy_evaluation:latest-dev
    command: sleep infinity
    volumes:
      - .:/docker-ros/ws/src/target
      - ${HOME}/.claude:/root/.claude

  ## DATASET ##

  autonomy_datasets:
    extends:
      file: docker-compose.yml
      service: autonomy_datasets
    # image: ghcr.io/thinking-cars/autonomy_datasets:latest-dev
    # command: sleep infinity
    # volumes:
    #   - ../autonomy_datasets:/docker-ros/ws/src/target
    #   - ${HOME}/.claude:/root/.claude

  ## SYSTEM UNDER TEST ##

  autoware_lidar_centerpoint:
    extends:
      file: docker-compose.yml
      service: autoware_lidar_centerpoint

  focalformer3d-detector:
    extends:
      file: docker-compose.yml
      service: focalformer3d-detector
