/**/*:
  ros__parameters:

    dataset: waymo_open_dataset
    dataset_split: validation  # all, training, validation
    waymo_min_lidar_points_in_bbox: 1
    waymo_lidar_object_list_filter_cam_front: false

    publish_ego_data: false
    publish_camera_images: false
    publish_camera_all_object_lists: false
    publish_camera_01_object_lists: false
    publish_lidar_01_pointclouds: true
    publish_lidar_01_object_lists: true